server:
    port: 8080

spring:
    application:
        name: account
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:Post123321}
        driver-class-name: org.postgresql.Driver
    flyway:
        baseline-on-migrate: true
        schemas: account
    jpa:
        properties:
        hibernate:
            default_schema: account
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

management:
    endpoints:
        web:
            base-path: /account/actuator
            exposure:
                include: [ 'prometheus' ]

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}